name: Trigger Render Schedule

on:
  schedule:
    - cron: '0 0 * * *' # Midnight UTC
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: POST to Render App
        run: |
          curl -X POST https://new-music-releases.onrender.com/api/trigger-schedule \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.TRIGGER_TOKEN }}" \
            -d '{}' \
            --fail --show-error --max-time 300
